// Author: Steven Goldade
#ifndef _NES_NAMETABLE_H_
#define _NES_NAMETABLE_H_
#include "../core.h"
/**
 * Inserts data into the PPU update buffer to update the given nametable with the provided data.
 * This update happens during the vertical blanking NMI generated by the PPU.
 *
 * @param data the data to copy to the nametable
 * @param size the size of the data to copy
 * @param nametable the nametable to copy to (0-3)
 * @param x the x value on the nametable for the start of the data (0-31) (32 is like writing to the next line)
 * @param y the y value on the nametable for the start of the data (0-29) (30 & 31 will write attribute table!) (32 wraps back to 0)
 */
extern void __fastcall__ ppu_nmi_nt_update(const u8* data, u8 size, u8 nametable, u8 x, u8 y);

extern const u8* NAMETABLE_0;
extern const u8* NAMETABLE_1;
extern const u8* NAMETABLE_2;
extern const u8* NAMETABLE_3;

#define NT_WIDTH 32
#define NT_HEIGHT 30
#define NT0_ADDR(x,y) ((u16)(&NAMETABLE_0) | (y << 5) | x)
#define NT1_ADDR(x,y) ((u16)(&NAMETABLE_1) | (y << 5) | x)
#define NT2_ADDR(x,y) ((u16)(&NAMETABLE_2) | (y << 5) | x)
#define NT3_ADDR(x,y) ((u16)(&NAMETABLE_3) | (y << 5) | x)

#endif //_NES_NAMETABLE_H_