// Author: Steven Goldade
#ifndef _TILESET_H_
#define _TILESET_H_

#define SPRITE_CHARACTER_SOUTH_LEFT 0
#define SPRITE_CHARACTER_SOUTH_STAND_LEFT 1
#define SPRITE_CHARACTER_SOUTH_WALK_LEFT 2
#define SPRITE_CHARACTER_SOUTH_WALK_RIGHT 3
#define SPRITE_CHARACTER_NORTH_LEFT 4
#define SPRITE_CHARACTER_NORTH_STAND_LEFT 5
#define SPRITE_CHARACTER_NORTH_WALK_LEFT 6
#define SPRITE_CHARACTER_NORTH_WALK_RIGHT 7
#define SPRITE_CHARACTER_EAST_TOP 8
#define SPRITE_CHARACTER_EAST_STAND 9
#define SPRITE_CHARACTER_EAST_WALK_1 10
#define SPRITE_CHARACTER_EAST_WALK_2 11

#endif